title: Andreas Charalampopoulos' Homepage
page-top-title: Andreas Charalampopoulos
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Andreas Charalampopoulos 2024-2025. All Rights Reserved.'
